import type { Locale } from "@/i18n/config";
import type { ProjectCategory } from "@/types/content";

export const publicCopy = {
  fr: {
    home: {
      eyebrow: "Élève ingénieur · Cybersécurité & IA",
      title: "Je construis des systèmes utiles à l'intersection du logiciel, de la sécurité et de l'IA.",
      introduction:
        "Je suis Amine Nahli, élève ingénieur en génie informatique à l'Université Privée de Fès. J'explore des problèmes concrets par le développement full-stack, l'audit de sécurité et l'intelligence artificielle.",
      primaryCta: "Découvrir mes projets",
      secondaryCta: "Voir mon parcours",
      resumeCta: "Consulter mon CV",
      proofEyebrow: "Profil en bref",
      proofTitle: "Une formation d'ingénieur nourrie par la pratique.",
      proofDescription:
        "Mes travaux relient applications métier, sécurité des accès, réseaux et modèles d'intelligence artificielle.",
      proofItems: [
        ["Formation", "3e année de génie informatique à l'UPF"],
        ["Expérience actuelle", "Stage PFA Cybersécurité & IA chez IntelTrust"],
        ["Langues", "Arabe maternel · Français courant · Anglais intermédiaire"],
      ],
      projectsEyebrow: "Sélection",
      projectsTitle: "Des projets qui croisent plusieurs disciplines.",
      projectsDescription: "Trois réalisations techniques documentées dans mon CV officiel.",
      allProjects: "Voir tous les projets",
      skillsEyebrow: "Compétences",
      skillsTitle: "Des compétences reliées à des réalisations concrètes.",
      skillsDescription: "Pas de pourcentages arbitraires : chaque domaine est présenté avec ses technologies et ses preuves de pratique.",
      allSkills: "Explorer les compétences",
      nowEyebrow: "Maintenant",
      nowTitle: "Ce sur quoi je travaille actuellement.",
      nowDescription: "Une vue concise de mon activité, fondée sur la dernière version validée de mon CV.",
      nowCta: "Voir la page Maintenant",
      certificationsEyebrow: "Certifications",
      certificationsTitle: "Apprentissage continu et pratique structurée.",
      certificationsCta: "Voir les certifications",
      contactEyebrow: "Échangeons",
      contactTitle: "Vous souhaitez parler d'un projet, d'un stage ou d'une opportunité ?",
      contactDescription: "Retrouvez mes coordonnées et mes profils professionnels sur la page contact.",
      contactCta: "Me contacter",
    },
    projects: {
      eyebrow: "Réalisations",
      title: "Projets techniques",
      description: "Une sélection de systèmes développés en ingénierie logicielle, cybersécurité, IA et embarqué.",
      searchLabel: "Rechercher un projet",
      searchPlaceholder: "Nom, technologie ou sujet…",
      categoryLabel: "Filtrer par domaine",
      sortLabel: "Trier les projets",
      allCategories: "Tous les domaines",
      sortFeatured: "Mis en avant",
      sortAlphabetical: "Ordre alphabétique",
      resultCount: (count: number) => `${count} projet${count > 1 ? "s" : ""}`,
      empty: "Aucun projet ne correspond à ces critères.",
      reset: "Réinitialiser les filtres",
      viewProject: "Voir le projet",
      documentedResults: "Résultats documentés",
      architecture: "Architecture",
      technologies: "Technologies",
      overview: "Présentation",
      problem: "Problème traité",
      objectives: "Objectifs",
      solution: "Solution technique",
      sourceCode: "Voir le code source",
      liveDemo: "Ouvrir la démonstration",
      sourceNote: "Les informations publiées sur cette page proviennent du CV officiel. Les éléments non documentés ne sont pas affichés.",
      back: "Retour aux projets",
    },
    skills: {
      eyebrow: "Pratique technique",
      title: "Compétences",
      description: "Une cartographie honnête des domaines travaillés, sans score ni pourcentage subjectif.",
      evidence: "Projets associés",
      viewProject: "Voir le projet",
    },
    certifications: {
      eyebrow: "Formation continue",
      title: "Certifications et parcours",
      description: "Les intitulés repris ici correspondent aux éléments présents dans mon CV officiel.",
      completed: "Terminé",
      relatedSkills: "Compétences associées",
      verify: "Consulter le profil de vérification",
    },
    journey: {
      eyebrow: "Parcours",
      title: "Une progression entre ingénierie logicielle, cybersécurité et IA.",
      description: "Cette chronologie rassemble uniquement les formations et expériences documentées dans mon CV.",
      experience: "Expérience",
      education: "Formation",
    },
    now: {
      eyebrow: "Maintenant",
      title: "Ce que je fais en ce moment",
      description: "Une photographie concise de mon activité professionnelle actuelle.",
      currentProject: "Contexte actuel",
      currentWork: "Travail en cours",
      objective: "Fil conducteur",
      updated: "Dernière mise à jour : juillet 2026",
      source: "Source : CV officiel, version actuellement fournie avec ce portfolio.",
    },
    contact: {
      eyebrow: "Contact",
      title: "Commençons une conversation.",
      description: "Pour une opportunité, une collaboration ou un échange technique, vous pouvez me joindre directement ou utiliser l'un de mes profils professionnels.",
      email: "Écrire par e-mail",
      linkedin: "Voir LinkedIn",
      github: "Voir GitHub",
      formLater: "Le formulaire sécurisé sera disponible après la mise en place de son stockage et de ses protections anti-spam.",
    },
    blog: {
      eyebrow: "Blog",
      title: "Notes techniques et retours d'expérience",
      description: "Les articles seront publiés ici après rédaction, relecture et validation humaine.",
    },
    notFound: {
      eyebrow: "Erreur 404",
      title: "Cette page n'existe pas ou a été déplacée.",
      description: "Revenez à l'accueil ou poursuivez votre exploration depuis la navigation principale.",
      home: "Revenir à l'accueil",
    },
  },
  en: {
    home: {
      eyebrow: "Engineering student · Cybersecurity & AI",
      title: "I build useful systems at the intersection of software, security and AI.",
      introduction:
        "I'm Amine Nahli, a computer engineering student at Université Privée de Fès. I explore practical problems through full-stack development, security auditing and artificial intelligence.",
      primaryCta: "Explore my projects",
      secondaryCta: "View my journey",
      resumeCta: "Open my resume",
      proofEyebrow: "Profile at a glance",
      proofTitle: "An engineering education strengthened by hands-on practice.",
      proofDescription: "My work connects business applications, access security, networks and artificial intelligence models.",
      proofItems: [
        ["Education", "Third-year computer engineering student at UPF"],
        ["Current experience", "Cybersecurity & AI PFA internship at IntelTrust"],
        ["Languages", "Native Arabic · Fluent French · Intermediate English"],
      ],
      projectsEyebrow: "Selected work",
      projectsTitle: "Projects across multiple disciplines.",
      projectsDescription: "Three technical projects documented in my official resume.",
      allProjects: "View all projects",
      skillsEyebrow: "Skills",
      skillsTitle: "Skills connected to tangible work.",
      skillsDescription: "No arbitrary percentages: each field is presented through its technologies and evidence of practice.",
      allSkills: "Explore skills",
      nowEyebrow: "Now",
      nowTitle: "What I'm working on right now.",
      nowDescription: "A concise view of my current activity, based on the latest validated version of my resume.",
      nowCta: "View the Now page",
      certificationsEyebrow: "Certifications",
      certificationsTitle: "Continuous learning and structured practice.",
      certificationsCta: "View certifications",
      contactEyebrow: "Let's talk",
      contactTitle: "Would you like to discuss a project, internship or opportunity?",
      contactDescription: "Find my contact details and professional profiles on the contact page.",
      contactCta: "Contact me",
    },
    projects: {
      eyebrow: "Selected work",
      title: "Technical projects",
      description: "A selection of systems developed across software engineering, cybersecurity, AI and embedded computing.",
      searchLabel: "Search projects",
      searchPlaceholder: "Name, technology or topic…",
      categoryLabel: "Filter by field",
      sortLabel: "Sort projects",
      allCategories: "All fields",
      sortFeatured: "Featured first",
      sortAlphabetical: "Alphabetical order",
      resultCount: (count: number) => `${count} project${count === 1 ? "" : "s"}`,
      empty: "No projects match these criteria.",
      reset: "Reset filters",
      viewProject: "View project",
      documentedResults: "Documented results",
      architecture: "Architecture",
      technologies: "Technologies",
      overview: "Overview",
      problem: "Problem addressed",
      objectives: "Objectives",
      solution: "Technical solution",
      sourceCode: "View source code",
      liveDemo: "Open live demo",
      sourceNote: "The information on this page comes from the official resume. Undocumented details are not displayed.",
      back: "Back to projects",
    },
    skills: {
      eyebrow: "Technical practice",
      title: "Skills",
      description: "An honest map of the fields I have worked in, without subjective scores or percentages.",
      evidence: "Related projects",
      viewProject: "View project",
    },
    certifications: {
      eyebrow: "Continuous learning",
      title: "Certifications and learning paths",
      description: "The titles shown here match the items listed in my official resume.",
      completed: "Completed",
      relatedSkills: "Related skills",
      verify: "Open verification profile",
    },
    journey: {
      eyebrow: "Journey",
      title: "Progress across software engineering, cybersecurity and AI.",
      description: "This timeline includes only the education and experience documented in my resume.",
      experience: "Experience",
      education: "Education",
    },
    now: {
      eyebrow: "Now",
      title: "What I'm doing now",
      description: "A concise snapshot of my current professional activity.",
      currentProject: "Current context",
      currentWork: "Work in progress",
      objective: "Guiding direction",
      updated: "Last updated: July 2026",
      source: "Source: the official resume currently supplied with this portfolio.",
    },
    contact: {
      eyebrow: "Contact",
      title: "Let's start a conversation.",
      description: "For an opportunity, collaboration or technical exchange, you can reach me directly or use one of my professional profiles.",
      email: "Send an email",
      linkedin: "View LinkedIn",
      github: "View GitHub",
      formLater: "The secure form will be available once its storage and anti-spam protections are in place.",
    },
    blog: {
      eyebrow: "Blog",
      title: "Technical notes and lessons learned",
      description: "Articles will appear here after writing, review and human validation.",
    },
    notFound: {
      eyebrow: "404 error",
      title: "This page does not exist or has moved.",
      description: "Return home or continue exploring from the main navigation.",
      home: "Return home",
    },
  },
} as const;

export const projectCategoryLabels: Record<ProjectCategory, Record<Locale, string>> = {
  software: { fr: "Ingénierie logicielle", en: "Software engineering" },
  cybersecurity: { fr: "Cybersécurité", en: "Cybersecurity" },
  "artificial-intelligence": { fr: "Intelligence artificielle", en: "Artificial intelligence" },
  embedded: { fr: "Systèmes embarqués", en: "Embedded systems" },
};
